# Generated by Django 2.1.2 on 2018-10-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0003_auto_20181010_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='bottom_right_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='bottom_right_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='top_left_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='top_left_width',
            field=models.IntegerField(default=0),
        ),
    ]
