# Generated by Django 2.1.2 on 2018-10-12 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0004_auto_20181012_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='bottom_right_height',
        ),
        migrations.RemoveField(
            model_name='document',
            name='bottom_right_width',
        ),
        migrations.RemoveField(
            model_name='document',
            name='top_left_height',
        ),
        migrations.RemoveField(
            model_name='document',
            name='top_left_width',
        ),
    ]
