# Generated by Django 2.1.2 on 2018-10-12 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0005_auto_20181012_1632'),
    ]

    operations = [
        migrations.DeleteModel(
            name='document',
        ),
    ]
